### ISSUE TITLE
can't cope with Haddock comments

### ISSUE THREAD

**Issue by peterbecich** [Simspace/simformat#32]
i.e.

```
-- | my imports
import X.Y.Z
```

**Comment by rickowens** [comment]
I think it is worth pointing out that import statements are not valid Haddock targets in the first place though and will in fact cause Haddock to crash, but I suspect this is still a problem for normal comments.

Also, just some random thoughts: It might be tricky to support comments like this because simformat can't know what the comment "means". What is it documenting exactly and where should it be put when the order of all the import statements completely changes? Probably the best thing would be to treat the comment like a blank line, which means it creates a "group" of imports like normal blank lines do. But that still leaves open the question of what to do about this:

```
import Control.Lens        -- Once upon a midnight dreary, while I pondered, weak and weary,
import Data.Aeson          -- Over many a quaint and curious volume of forgotten lore—
import Data.Set            --     While I nodded, nearly napping, suddenly there came a tapping,
import Control.Applicative -- As of some one gently rapping, rapping at my chamber door.
import Servant.API.Generic -- “’Tis some visitor,” I muttered, “tapping at my chamber door—
import Data.Map            --             Only this and nothing more.”
```

I specifically chose something random to go in the comments to illustrate the fact that it is difficult to know what the programmer is trying to express.

One solution might be:
1. remove all comments
2. run the normal simformat logic
3.
    1. If step 2 resulted in no change, then do not change the file (i.e. leave the comments as is).
    2. If step 2 resulted in a change, then apply the change and just blow away the comments, forcing the developer to add them back with `git` or whatever.

**Comment by gelisam** [comment]
This uncertainty is precisely the reason why simformat currently gives up when it encounters a comment. @laurenthuberdeau added support for commented-out imports (e.g. `-- import Foo`, not `import Foo  -- my comment`), so I am guessing he has some thoughts on this issue.
